### ISSUE TITLE
支持css-module 的写法吗

### ISSUE THREAD

**Issue by coderzzp** [MrGaoGang/parse-jsx-to-css#1]

**Comment by MrGaoGang** [comment]
暂时还不支持react/vue中的css 变量写法; 使用css-module是先知道css名称再去写className，然而这个解析器主要是将div/其他标签的class解析成Less/css中的结构

**Comment by MrGaoGang** [comment]
> No description provided.

暂时还不支持react/vue中的css 变量写法; 使用css-module是先知道css名称再去写className，然而这个解析器主要是将div/其他标签的class解析成Less/css中的结构；后续可以考虑支持css变量的写法，但是需要依赖于上下文去解析class的名称应该有哪些
